package com.ebikes.routing.enums;

public enum PricingModifierType {
  FIXED_SURCHARGE,
  FIXED_DISCOUNT,
  PERCENT_SURCHARGE,
  PERCENT_DISCOUNT,
  MIN_PRICE_FLOOR,
  MAX_PRICE_CAP,
  PEAK_WINDOW_SURCHARGE,
  ORDER_TYPE_SURCHARGE,
  ORDER_TYPE_DISCOUNT
}
